table_names = [r"\NHDPlusGlobalData\BoundaryUnit (feature class) ",
               r"\NHDPlusGlobalData\SuperCatchments (feature class) ",
               r"\NHDPlusGlobalData\SC<featureid> (grid) ",
               "bad",
               r"\NHDPlusNationalData\GageLoc (feature class) ",
               r"\NHDPlusNationalData\GageInfo (table) ",
               r"\NHDPlusNationalData\Gage_Smooth (table) ",
               r"\NHDPlusNationalData\nationalcat (grid) ",
               r"bad",
               r"\NHDPlusCatchment\FeatureIDGridcode (table) ",
               r"\NHDPlusCatchment\cat (grid) ",
               r"\NHDPlusCatchment\Catchment (polygon feature class) ",
               r"\NHDPlusAttributes\CumulativeArea (table) ",
               r"\NHDPlusAttributes\DivFracMP (table) ",
               r"\NHDPlusAttributes\ElevSlope (table) ",
               r"\NHDPlusAttributes\HeadwaterNodeArea (table) ",
               r"\NHDPlusAttributes\MegaDiv (table) ",
               r"\NHDPlusAttributes\PlusWaterbodyLakeMorphology (table) ",
               r"\NHDPlusAttributes\PlusFlowlineLakeMorphology (table) ",
               r"\NHDPlusAttributes\PlusFlowlineVAA (table) ",
               r"\NHDPlusAttributes\PlusFlowlineVAA (table) ",
               r"\NHDPlusAttributes\PlusFlow (table) ",
               r"\NHDPlusAttributes\PlusARPointEvent (table) ",
               r"bad",
               r"\NHDPlusAttributes\PlusFlowAR (table) ",
               r"\NHDPlusFdrFacrrrrrrrr\fac (grid) ",
               r"\NHDPlusFdrFacrrrrrrrr\fdr (grid) ",
               r"\NHDPlusFilledAreasrrrrrrrr\filledareas (grid) ",
               r"\NHDPlusCatSeedrrrrrrrr\catseed (grid) ",
               r"\NHDPlusFdrNullrrrrrrrr\fdrnull (grid) ",
               r"\NHDPlusHydroDemrrrrrrrr\hydrodem (grid) ",
               r"\NHDPlusBurnComponents\BurnLineEvent (table) ",
               r"\NHDPlusBurnComponents\BurnWaterbody (polygon feature class) ",
               r"\NHDPlusBurnComponents\Sink (point feature class) ",
               r"\NHDPlusBurnComponents\Wall (line feature class) ",
               r"\NHDPlusBurnComponents\LandSea (polygon feature class) ",
               r"\NHDPlusBurnComponents\BurnAddLine (line feature class) ",
               r"\NHDPlusBurnComponents\BurnAddWaterbody (polygon feature class) ",
               r"bad",
               r"\EROMExtension\EROM_MA0001 and EROM_mm0001 (tables) ",
               r"\EROMExtension\EROMQA_0001 (pdf) ",
               r"\EROMExtension\EROMQA_MA0001 and EROMQA_mm0001 (tables) ",
               r"\VogelExtension\VogelFlow (table) ",
               r"\VPUAttributeExtension\IncrLat (comma delimited table) ",
               r"\VPUAttributeExtension\ROMA and ROMMmm (comma delimited tables) ",
               r"\NHDPlusAttributeExtension\CumTotROMA, CumDivROMA, CumTotROMMmm, CumDivROMMmm (comma delimited tables) ",
               r"\NHDPlusAttributeExtension\IncrPrecipMA and IncrPrecipMMmm (comma delimited tables) ",
               r"\NHDPlusAttributeExtension\CumTotPrecipMA, CumDivPrecipMA, CumTotPrecipMMmm, and CumDivPrecipMMmm (comma delimited tables) ",
               r"\NHDPlusAttributeExtension\IncrTempMA and IncrTempMMmm (comma delimited tables) ",
               r"\NHDPlusAttributeExtension\CumTotTempMA, CumDivTempMA, CumTotTempMMmm, and CumDivTempMMmm (comma delimited tables) "]
